###Endpoint Task 2.1
GET localhost:8585/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODIwNDY1NzQsImlhdCI6MTY4MTk2MDE3NCwic3ViIjoiRGFtaXIifQ.3RogSSPC-zGaD7vDIF9bzLmIAg0xPgoETQbzyMpJDg0
Content-Type: application/json
###Endpoint Task 2.2
GET localhost:8585/api/v1/records/month
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODIwNDY1NzQsImlhdCI6MTY4MTk2MDE3NCwic3ViIjoiRGFtaXIifQ.3RogSSPC-zGaD7vDIF9bzLmIAg0xPgoETQbzyMpJDg0
Content-Type: application/json

{
  "Email": "test"
}
###Update Password
POST localhost:8585/api/v1/password
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODExMzI5NzgsImlhdCI6MTY4MTA0NjU3OCwic3ViIjoidGVzdCJ9.tr25SngsA7Sn2xsJLofpUPBz505q72run3KXkXPbUrE
Content-Type: application/json

{
  "Password":"123"
}

### Register User
POST localhost:8585/api/v1/user
Content-Type: application/json

{
    "Name":"Damir",
    "Email":"Damir",
    "Password":"12345"
}
###Login Get Token
POST localhost:8585/api/v1/login
Content-Type: application/json

{
  "Email":"Damir",
  "Password":"12345"
}
###Add Book
POST localhost:8585/api/v1/book
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODIwNDY1NzQsImlhdCI6MTY4MTk2MDE3NCwic3ViIjoiRGFtaXIifQ.3RogSSPC-zGaD7vDIF9bzLmIAg0xPgoETQbzyMpJDg0
Content-Type: application/json

{
  "Title": "Java Book Vol.10",
  "Author": "DamirG"
}

### Add Record
POST localhost:8585/api/v1/borrow
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODIwNDY1NzQsImlhdCI6MTY4MTk2MDE3NCwic3ViIjoiRGFtaXIifQ.3RogSSPC-zGaD7vDIF9bzLmIAg0xPgoETQbzyMpJDg0
Content-Type: application/json

{
  "UID": 1,
  "BID": 3,
  "Price": 5000
}
### Get All Borrowed Books With Revenue
GET localhost:8585/api/v1/books/borrowed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODIwNDY1NzQsImlhdCI6MTY4MTk2MDE3NCwic3ViIjoiRGFtaXIifQ.3RogSSPC-zGaD7vDIF9bzLmIAg0xPgoETQbzyMpJDg0
Content-Type: application/json


### Get All Records of the user
GET localhost:8585/api/v1/records
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODIwNDY1NzQsImlhdCI6MTY4MTk2MDE3NCwic3ViIjoiRGFtaXIifQ.3RogSSPC-zGaD7vDIF9bzLmIAg0xPgoETQbzyMpJDg0
Content-Type: application/json

{
  "Email": "test"
}
### Get Transaction
GET localhost:8787/api/v1/transaction/2
Content-Type: application/json

